---
- name: Lookup secret
  ansible.builtin.set_fact:
    rds_msgc_host: "{{ lookup('amazon.aws.aws_secret.aws_secret', rds_secret_host_name, region=aws_region, nested=true) }}"
    rds_msgc_password: "{{ lookup('amazon.aws.aws_secret.aws_secret', rds_secret_password_name, region=aws_region, nested=true) }}"
    rds_msgc_username: "{{ lookup('amazon.aws.aws_secret.aws_secret', rds_secret_username, region=aws_region, nested=true) }}"
    rds_msgc_db_name: "{{ lookup('amazon.aws.aws_secret.aws_secret', rds_secret_db_name, region=aws_region, nested=true) }}"
    unagi_ca_privkey: "{{ lookup('amazon.aws.aws_secret.aws_secret', unagi_ca_privkey_secret_name, region=aws_region) }}"
    unagi_ca_pubkey: "{{ lookup('amazon.aws.aws_secret.aws_secret', unagi_ca_pubkey_secret_name, region=aws_region) }}"

- name: Create msgc namespace
  kubernetes.core.k8s:
    name: "{{ msgc_namespace }}"
    kind: Namespace
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy secret.yml
  kubernetes.core.k8s:
    state: present
    template: "secret.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy deployment.yml
  kubernetes.core.k8s:
    state: present
    template: "deployment.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy service.yml
  kubernetes.core.k8s:
    state: present
    template: "service.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy configmap.yml
  kubernetes.core.k8s:
    state: present
    template: "configmap.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy ingress.yml
  kubernetes.core.k8s:
    state: present
    template: "ingress.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy network.yml
  kubernetes.core.k8s:
    state: present
    template: "network.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"
