{
 "title": "Datacore",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service", "query": "Datacore" },
   {
    "name": "route",
    "query": {
     "query": "label_values({app=\"$service\"}, route)"
    }
   },
   {
    "name": "quantile",
    "query": {
     "query": "label_values(http_request_duration_summary{app=\"$service\"}, quantile)"
    }
   },
   { "name": "callOutStatus", "label": "CallStatus", "query": { "query": "label_values(callOutStatus)" } }
  ]
 },
 "panels": [
  {
   "title": "req-count-callout",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{le=\"+Inf\",route=\"/callout/makeCall\"}[1h]))",
     "legendFormat": "make-call"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{le=\"+Inf\",route=\"/callout/accessToken\"}[1h]))",
     "legendFormat": "access-token"
    }
   ]
  },
  {
   "title": "req-increased",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{le=\"+Inf\",route=~\"$route\"}[1h]))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_summary{route=~\"$route\",app=~\"$service\",quantile=~\"$quantile\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Login Number",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(login_metric{route=~\"$route\"}[2d])) by (app,date) > 0",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "Complete Call Out Number ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(call_duration_histogram_count{callOutStatus=\"completed\"})",
     "legendFormat": "{{callOutStatus}}"
    }
   ]
  },
  {
   "title": "Call Out Number",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(call_duration_histogram_count{callOutStatus=~\"completed|busy|no-answer|canceled|failed\"})",
     "legendFormat": "{{callOutStatus}}"
    }
   ]
  },
  {
   "title": "Failed Call Out Number",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(call_duration_histogram_count{callOutStatus=\"failed\"})",
     "legendFormat": "{{callOutStatus}}"
    }
   ]
  },
  {
   "title": "Req count ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_seconds_bucket{le=\"+Inf\",route=~\"$route\"}[1m])) by (route)",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "Avrage response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(http_request_duration_seconds_sum{app=~\"$service\",route=~\"$route\"}[60s])/delta(http_request_duration_seconds_count{app=~\"$service\",route=~\"$route\"}[60s])",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  }
 ]
}