{
 "title": "MSGC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "reqType",
    "query": {
     "query": "label_values(msgc_ws_frame_duration_milliseconds_sum,type)"
    }
   },
   {
    "name": "le",
    "query": {
     "query": "label_values(msgc_ws_frame_duration_milliseconds_bucket,le)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration bucket (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "msgc_ws_frame_duration_milliseconds_bucket{le=~\"$le\",type=~\"$reqType\"}",
     "legendFormat": "{{le}}-{{type}}"
    }
   ]
  },
  {
   "title": "Req count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(msgc_ws_frame_duration_milliseconds_bucket{le=\"+Inf\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avrage response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(msgc_ws_frame_duration_milliseconds_sum{type=~\"$reqType\"}[60s])/delta(msgc_ws_frame_duration_milliseconds_count{type=~\"$reqType\"}[60s])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}