{
 "title": "Ns Resource Usage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ns",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$ns\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (instance) (container_memory_usage_bytes{namespace=~\"$ns\"}))"
    }
   ]
  },
  {
   "title": "Total Servers Core",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores {instance=~\"$node\"}) "
    }
   ]
  },
  {
   "title": "Total Servers RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes {instance=~\"$node\"}) "
    }
   ]
  },
  {
   "title": "Total Requested CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=~\"$ns\",node=~\"$node\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Total Requested RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=~\"$ns\",node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{namespace=~\"$ns\",container!~\"POD|\",nodename=~\"$node\"}[2m]))"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=~\"$ns\",container!~\"POD|\",nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cpu Core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (irate(container_cpu_usage_seconds_total{namespace=\"$ns\",nodename=~\"$node\"}[2m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$ns\",nodename=~\"$node\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (label_replace(irate(container_network_transmit_bytes_total{namespace=\"$ns\",nodename=~\"$node\"}[2m]) ,\"app\",\"$1\",\"pod\", \"(.*)-(.*)-(.*)\"))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (label_replace(irate(container_network_receive_bytes_total{namespace=\"$ns\",nodename=~\"$node\"}[2m]) ,\"app\",\"$1\",\"pod\", \"(.*)-(.*)-(.*)\"))",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}