{
 "title": "Pod's Resource Monitor",
 "description": "Monitor pods usage and throttle stats, requests and limits for cpu and memory.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\", container=~\"$containers\"}) or sum by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$containers\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\", container=~\"$containers\"}[2m])) by (pod) or sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name!=\"\", container_name!=\"POD\", container_name=~\"$containers\"}[2m])) by (pod_name)",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Throttle (Percentage)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}[5m])) / sum by (container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m]))",
     "legendFormat": "{{pod}} {{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$containers\"}[2m])",
     "legendFormat": "{{pod}} {{nodename}}"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[10m]) )",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[10m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Traffic transmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or irate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic receive",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\"}[2m]) or irate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m]) ",
     "legendFormat": "Reads {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", container!=\"\", container!=\"POD\"}[5m])",
     "legendFormat": "Writes {{ device }} [{{ pod }} / {{ container }}]"
    }
   ]
  }
 ]
}