---
- name: Lookup secret
  ansible.builtin.set_fact:
    docdb_datacore_host: "{{ lookup('amazon.aws.aws_secret.aws_secret', docdb_secret_host_name, region=aws_region, nested=true) }}"
    docdb_datacore_password: "{{ lookup('amazon.aws.aws_secret.aws_secret', docdb_secret_password_name, region=aws_region, nested=true) }}"
    docdb_datacore_username: "{{ lookup('amazon.aws.aws_secret.aws_secret', docdb_secret_username, region=aws_region, nested=true) }}"
    twilio_account_sid: "{{ lookup('amazon.aws.aws_secret.aws_secret', 'twillio-meta.twilio_account_sid', region='eu-west-1', nested=true) }}"
    twilio_auth_token: "{{ lookup('amazon.aws.aws_secret.aws_secret', 'twillio-meta.twillio_auth_token', region='eu-west-1', nested=true) }}"
    send_grid_api_key: "{{ lookup('amazon.aws.aws_secret.aws_secret', 'twillio-meta.send_grid_api_key', region='eu-west-1', nested=true) }}"
    notification_google_service_account: "{{ lookup('amazon.aws.aws_secret.aws_secret', 'notification-google-service-account', region='eu-west-1') }}"
    unagi_ca_pubkey: "{{ lookup('amazon.aws.aws_secret.aws_secret', unagi_ca_pubkey_secret_name, region=aws_region) }}"

- name: Create notification namespace
  kubernetes.core.k8s:
    name: "{{ notification_namespace }}"
    kind: Namespace
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy secret.yml
  kubernetes.core.k8s:
    state: present
    template: "secret.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy deployment.yml
  kubernetes.core.k8s:
    state: present
    template: "deployment.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy configmap.yml
  kubernetes.core.k8s:
    state: present
    template: "configmap.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy service.yml
  kubernetes.core.k8s:
    state: present
    template: "service.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"

- name: Deploy ingress.yml
  kubernetes.core.k8s:
    state: present
    template: "ingress.yml.j2"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"
