---
- name: Add bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy rabbitmq
  kubernetes.core.helm:
    name: ingress-nginx-memcached
    chart_ref: bitnami/memcached
    release_namespace: "ingress-nginx"
    update_repo_cache: true
    chart_version: "6.5.5"
    values: "{{ lookup('template', 'memcached-value-file.yml.j2') | from_yaml }}"
    kubeconfig: "~/.kube/{{ project }}-eks-main-{{ env }}"
